### ISSUE TITLE
Axis movement problem

### ISSUE THREAD

**Issue by FireCatNZ** [Mattalabs/OctoPrint-Mattacloud#11]
Mattacloud connects to my printer fine (can't get video to work yet though), but axis control always goes in the same direction. 
On the Z axis, up & down both go up. On the X axis left & right both go right. 
Octoprint & The Spaghetti Detective control all the axis movement normally.
Ender 3 Pro, with SKR Mini E3 v1.2 motherboard and Marlin 2.0.5.3 
OctoPrint 1.4.2, Python 3.7.3, OctoPi 0.17.0.

**Comment by dougbrion** [comment]
Let me quickly look into this... very bizarre!

**Comment by dougbrion** [comment]
Okay hopefully this is fixed now, let me know if not!
