### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by lloydbigoil** [Mattalabs/OctoPrint-Mattacloud#18]
is this abandoned? you cant sign up for a new account anymore

**Comment by dougbrion** [comment]
No no not abandoned. So sorry about this... currently in a vary manic phase of my PhD and for the last few months haven't been able to put much time to this project. Currently, re-writing our backend to make things more stable which might be why you are having issues! I'll post back here when some things have been fixed.

**Comment by lloydbigoil** [comment]
✌️
